"""Shared admin console shell and assets for persona runtimes."""

from .fastapi import register_static_assets
from .adapter_health import (
    ADAPTER_HEALTH_FEATURE,
    adapter_health_feature_enabled,
    render_adapter_health_panel,
)
from .dashboard import (
    dashboard_metrics_from_counts,
    format_dashboard_metric_value,
    render_dashboard_activity,
    render_dashboard_adapter_cards,
    render_dashboard_attention,
    render_dashboard_filters,
    render_dashboard_flow,
    render_dashboard_health_strip,
    render_dashboard_metrics,
    render_dashboard_queue,
    render_dashboard_route_cards,
    render_dashboard_sections,
    render_dashboard_summary_grid,
)
from .models import (
    AdapterHealthCard,
    AdapterHealthConfig,
    AdapterHealthSparkBucket,
    ActivityEvent,
    ActivitySurfaceConfig,
    DashboardAction,
    DashboardActivityItem,
    DashboardAdapterCard,
    DashboardAttention,
    DashboardAttentionItem,
    DashboardData,
    DashboardFilter,
    DashboardFlow,
    DashboardFlowBucket,
    DashboardFlowSegment,
    DashboardHealthMetric,
    DashboardHealthStrip,
    DashboardMetric,
    DashboardMetricSpec,
    DashboardQueueRow,
    DashboardRouteCard,
    DashboardSparkBucket,
    MediaArtifactCard,
    MediaSurfaceConfig,
    MessageAttachment,
    MessageConversation,
    MessageSurfaceConfig,
    MessageTranscriptItem,
    NavGroup,
    NavItem,
    PeopleSurfaceConfig,
    PersonListRow,
    PersonRelationshipSummary,
    PersonTag,
    PersonaCoreConfig,
    PersonaConsoleConfig,
    ReviewAgendaItem,
    ReviewBoardRow,
    ReviewQueueCard,
    ReviewQueueSection,
    ReviewSurfaceConfig,
    StatusTab,
    StatusPill,
    SurfaceBadge,
    ThemeTokens,
    TokenHealthCheck,
    TokenHealthConfig,
    UserPill,
)
from .render import (
    active_nav_label,
    render_live_controls,
    render_nav_groups,
    render_shell_html,
    render_status_pill,
    render_user_pill,
)
from .controls import render_status_tabs
from .token_health import (
    TOKEN_HEALTH_FEATURE,
    build_token_health_report,
    render_token_health_panel,
    token_health_checks_for_providers,
    token_health_config_for_providers,
    token_health_feature_enabled,
    token_health_lookup,
    token_health_provider_keys,
)
from .surfaces import (
    ACTIVITY_FEATURE,
    MEDIA_FEATURE,
    MESSAGES_FEATURE,
    activity_surface_feature_enabled,
    media_surface_feature_enabled,
    message_surface_feature_enabled,
    render_activity_surface,
    render_media_surface,
    render_message_surface,
    render_surface_sections,
)
from .doctor import (
    ConsumerIntegrationDoctorReport,
    DoctorCheck,
    ModuleSnapshot,
    doctor_report_to_text,
    run_consumer_integration_doctor,
)
from .privacy import (
    OWNER_PRIVATE_ADMIN_FEATURE,
    WITHHELD_PRIVATE_TEXT,
    AdminPrivacyContext,
    OwnerPrivateScopePolicy,
    PrivacyRenderMode,
    can_view_raw_private,
    canonical_privacy_scope,
    feature_enabled,
    owner_private_scope_for_content,
    privacy_render_mode,
    render_private_text,
)
from .people import (
    PEOPLE_FEATURE,
    people_surface_feature_enabled,
    render_people_surface,
)
from .review import (
    REVIEW_FEATURE,
    render_review_surface,
    review_surface_feature_enabled,
)

__all__ = [
    "NavGroup",
    "ACTIVITY_FEATURE",
    "ADAPTER_HEALTH_FEATURE",
    "AdapterHealthCard",
    "AdapterHealthConfig",
    "AdapterHealthSparkBucket",
    "ActivityEvent",
    "ActivitySurfaceConfig",
    "DashboardAction",
    "DashboardActivityItem",
    "DashboardAdapterCard",
    "DashboardAttention",
    "DashboardAttentionItem",
    "DashboardData",
    "DashboardFilter",
    "DashboardFlow",
    "DashboardFlowBucket",
    "DashboardFlowSegment",
    "DashboardHealthMetric",
    "DashboardHealthStrip",
    "DashboardMetric",
    "DashboardMetricSpec",
    "DashboardQueueRow",
    "DashboardRouteCard",
    "DashboardSparkBucket",
    "MEDIA_FEATURE",
    "MESSAGES_FEATURE",
    "MediaArtifactCard",
    "MediaSurfaceConfig",
    "MessageAttachment",
    "MessageConversation",
    "MessageSurfaceConfig",
    "MessageTranscriptItem",
    "ConsumerIntegrationDoctorReport",
    "DoctorCheck",
    "ModuleSnapshot",
    "NavItem",
    "OWNER_PRIVATE_ADMIN_FEATURE",
    "PEOPLE_FEATURE",
    "AdminPrivacyContext",
    "OwnerPrivateScopePolicy",
    "PeopleSurfaceConfig",
    "PersonListRow",
    "PersonRelationshipSummary",
    "PersonTag",
    "PersonaCoreConfig",
    "PersonaConsoleConfig",
    "PrivacyRenderMode",
    "REVIEW_FEATURE",
    "ReviewAgendaItem",
    "ReviewBoardRow",
    "ReviewQueueCard",
    "ReviewQueueSection",
    "ReviewSurfaceConfig",
    "StatusTab",
    "StatusPill",
    "SurfaceBadge",
    "ThemeTokens",
    "TOKEN_HEALTH_FEATURE",
    "TokenHealthCheck",
    "TokenHealthConfig",
    "UserPill",
    "WITHHELD_PRIVATE_TEXT",
    "active_nav_label",
    "activity_surface_feature_enabled",
    "adapter_health_feature_enabled",
    "build_token_health_report",
    "can_view_raw_private",
    "canonical_privacy_scope",
    "configure_jinja_loader",
    "dashboard_metrics_from_counts",
    "doctor_report_to_text",
    "feature_enabled",
    "format_dashboard_metric_value",
    "media_surface_feature_enabled",
    "message_surface_feature_enabled",
    "people_surface_feature_enabled",
    "review_surface_feature_enabled",
    "owner_private_scope_for_content",
    "privacy_render_mode",
    "register_static_assets",
    "render_activity_surface",
    "render_dashboard_activity",
    "render_dashboard_adapter_cards",
    "render_dashboard_attention",
    "render_dashboard_filters",
    "render_dashboard_flow",
    "render_dashboard_health_strip",
    "render_dashboard_metrics",
    "render_dashboard_queue",
    "render_dashboard_route_cards",
    "render_dashboard_sections",
    "render_dashboard_summary_grid",
    "render_adapter_health_panel",
    "render_live_controls",
    "render_media_surface",
    "render_message_surface",
    "render_nav_groups",
    "render_people_surface",
    "render_private_text",
    "render_review_surface",
    "render_shell_html",
    "render_status_tabs",
    "render_status_pill",
    "render_surface_sections",
    "render_token_health_panel",
    "run_consumer_integration_doctor",
    "token_health_checks_for_providers",
    "token_health_config_for_providers",
    "token_health_feature_enabled",
    "render_user_pill",
    "token_health_lookup",
    "token_health_provider_keys",
]

__version__ = "1.0.15"


def configure_jinja_loader(*args, **kwargs):
    """Load the optional Jinja integration only when a consumer asks for it."""

    from .jinja import configure_jinja_loader as _configure_jinja_loader

    return _configure_jinja_loader(*args, **kwargs)
